// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo6tb2w4hHdQkwkdNzmlWYqMPPdI5KsOM',
    appId: '1:229026949839:web:97dc49c1349e6c1a1825ba',
    messagingSenderId: '229026949839',
    projectId: 'getready-94c66',
    authDomain: 'getready-94c66.firebaseapp.com',
    storageBucket: 'getready-94c66.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKaXB4OWVL-c3Ck6Liyzdiwr0q3q4NDS8',
    appId: '1:229026949839:android:b66a7d28e014588d1825ba',
    messagingSenderId: '229026949839',
    projectId: 'getready-94c66',
    storageBucket: 'getready-94c66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaWg-AibdYO7rPAjKT7OnRTFArkr5i2xo',
    appId: '1:229026949839:ios:6241b8864df35acb1825ba',
    messagingSenderId: '229026949839',
    projectId: 'getready-94c66',
    storageBucket: 'getready-94c66.appspot.com',
    iosClientId: '229026949839-79c2d65irvgl61runogc7l5870r0ejo4.apps.googleusercontent.com',
    iosBundleId: 'fr.getready.getReady',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaWg-AibdYO7rPAjKT7OnRTFArkr5i2xo',
    appId: '1:229026949839:ios:18436b0af37f04f61825ba',
    messagingSenderId: '229026949839',
    projectId: 'getready-94c66',
    storageBucket: 'getready-94c66.appspot.com',
    iosClientId: '229026949839-dpas0sph6fjkqf46rrvbuvjh5a3h5mb3.apps.googleusercontent.com',
    iosBundleId: 'fr.getready.getReady.RunnerTests',
  );
}
